CREATE TABLE "guestlist_guest" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guestlist_guest_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"phone" varchar(20),
	"email" varchar(256) NOT NULL,
	"note" text,
	"publicAction" varchar(100) NOT NULL,
	"role" varchar(50) NOT NULL,
	"displayNamePref" varchar(20) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "guestlist_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guestlist_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"aboutMe" text NOT NULL,
	"networkingStatement" text NOT NULL,
	"profilePictureUrl" varchar(500) NOT NULL,
	"linkedinUrl" varchar(500),
	"githubUrl" varchar(500),
	"buyMeACoffeeUrl" varchar(500),
	"portfolioUrl" varchar(500),
	"resumeUrl" varchar(500),
	"notificationEmail" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
DROP TABLE "guestlist_post" CASCADE;--> statement-breakpoint
CREATE INDEX "email_idx" ON "guestlist_guest" USING btree ("email");--> statement-breakpoint
CREATE INDEX "created_at_idx" ON "guestlist_guest" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "role_idx" ON "guestlist_guest" USING btree ("role");