CREATE TABLE "guestlist_resume" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "guestlist_resume_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fileName" varchar(256) NOT NULL,
	"fileUrl" varchar(500) NOT NULL,
	"fileSize" integer NOT NULL,
	"fileType" varchar(50) NOT NULL,
	"uploadThingId" varchar(100) NOT NULL,
	"isCurrent" boolean DEFAULT false NOT NULL,
	"downloadCount" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
ALTER TABLE "guestlist_guest" ADD COLUMN "hidden" boolean DEFAULT false NOT NULL;--> statement-breakpoint
CREATE INDEX "resume_upload_thing_id_idx" ON "guestlist_resume" USING btree ("uploadThingId");--> statement-breakpoint
CREATE INDEX "resume_is_current_idx" ON "guestlist_resume" USING btree ("isCurrent");--> statement-breakpoint
CREATE INDEX "resume_created_at_idx" ON "guestlist_resume" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "hidden_idx" ON "guestlist_guest" USING btree ("hidden");